
    <!-- Modal completo  -->
  <!--  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Bases y condiciones</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>


            <div class="modal-body">
              <ol start="1" style="margin-bottom:0cm;" type="1">
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;background:white;'><strong><u><span style='font-family:"Cambria",serif;color:black;'>BASES Y CONDICIONES PROMOCI&Oacute;N</span></u></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:center;background:white;'><strong><u><span style='font-family:"Cambria",serif;color:black;'>&ldquo;AXE EN LOLLA 2022&rdquo;</span></u></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>1. DESCRIPCI&Oacute;N.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>1.1.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>La siguiente promoci&oacute;n denominada <strong><u>&ldquo;AXE EN LOLLA 2022&rdquo;&nbsp;</u></strong>(en adelante, la &ldquo;Promoci&oacute;n&rdquo;) es organizada por UNILEVER DE ARGENTINA S.A. sita en Alf. H. Bouchard 4191, Munro, Ptdo. De Vte. L&oacute;pez, Prov. de Buenos Aires, Rep&uacute;blica Argentina (en adelante, el &ldquo;Organizador&rdquo;) para promocionar la venta de todas las l&iacute;neas de productos de la marca <strong><u>&ldquo;AXE&rdquo;</u></strong> en todas sus variedades y presentaciones (en adelante, el/los &ldquo;Producto/s&rdquo;). La presente Promoci&oacute;n es sin obligaci&oacute;n de compra de bienes o contrataci&oacute;n de servicios y quedar&aacute; sujeta a las siguientes bases y condiciones (en adelante, las &ldquo;Bases&rdquo;).</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>2. VIGENCIA. TERRITORIO.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>2.1.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>La Promoci&oacute;n se desarrollar&aacute; en&nbsp;</span><span style='font-size:14px;line-height:107%;font-family:"Cambria",serif;color:black;background:white;'>todo el territorio de la Rep&uacute;blica Argentina con excepci&oacute;n de las provincias de Salta, Mendoza, R&iacute;o Negro, Neuqu&eacute;n y Tierra del Fuego (en adelante, el &ldquo;Territorio&rdquo;), desde las 00:01 hs. del d&iacute;a 1 de Febrero de 2022 hasta las 23:59 hs. del d&iacute;a 6 de Marzo de 2022 ambas fechas inclusive (en adelante, el &ldquo;Plazo de Vigencia&rdquo;). El Plazo de Vigencia es improrrogable.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>3. CONDICIONES DE PARTICIPACI&Oacute;N.&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>3.1.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>Podr&aacute;n participar de la Promoci&oacute;n todas aquellas personas f&iacute;sicas mayores de dieciocho (18) a&ntilde;os, que est&eacute;n&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>presentes&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>en el Territorio y que sigan los mecanismos de participaci&oacute;n expuestos en estas Bases (en adelante, los &ldquo;Participantes&rdquo;).</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>3.2.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>No podr&aacute;n participar de esta Promoci&oacute;n, ni volverse acreedores de los Premios, personas f&iacute;sicas menores de dieciocho (18) a&ntilde;os, personas jur&iacute;dicas, el personal del Organizador ni de ninguna de las sociedades o empresas vinculadas con &eacute;ste, sus agencias de promoci&oacute;n ni dem&aacute;s personas que el Organizador contrate para proveer cualquier producto o cualquier servicio relacionado con la Promoci&oacute;n. Tampoco podr&aacute;n participar familiares directos de los mismos, o parientes por consanguinidad o afinidad hasta el segundo grado inclusive.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>4 MECANISMOS DE PARTICIPACI&Oacute;N.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>4.1.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>Aquellos interesados en&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>participar bajo alguna de las modalidades descriptas en este apartado</span><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>deber&aacute;n previamente contar con una cuenta que los identifique en las redes sociales Facebook y/o Instagram, cuya creaci&oacute;n es gratuita. Una vez cumplido dicho requisito, deber&aacute;n:</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>4.1.1. Participaci&oacute;n v&iacute;a Facebook</span></strong><span style='font-family:"Cambria",serif;color:black;'>: (i) estar atentos a los posteos patrocinados por el Organizador&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>en la red social Facebook (en adelante, el/los &ldquo;Posteo/s Patrocinado/s&rdquo;), en relaci&oacute;n a la Promoci&oacute;n, durante el Plazo de Vigencia; (ii) hacer click en el Posteo Patrocinado que los derivar&aacute; a un formulario (en adelante, el &ldquo;Formulario&rdquo;); (iii) completar el Formulario con sus datos personales, a saber, nombre, apellido y tel&eacute;fono (en adelante, los &ldquo;Datos de Contacto&rdquo;);</span><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>(iv) ingresar una respuesta a la pregunta que realizar&aacute; el Organizador en el Formulario, a saber, <em>&ldquo;&iquest;Cu&aacute;l es tu variedad favorita de AXE?&rdquo;</em>&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>(en adelante, la &ldquo;Pregunta&rdquo;)</span><span style='font-family:"Cambria",serif;color:black;'>; y (v) remitir su participaci&oacute;n haciendo click en &ldquo;Participar&rdquo;. Una vez cumplidos los pasos indicados, la participaci&oacute;n (en adelante, la &ldquo;Participaci&oacute;n&rdquo;) se encontrar&aacute; completa.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>4.1.2. Participaci&oacute;n v&iacute;a Instagram:&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>(i)<strong>&nbsp;</strong>estar atentos a los Posteos Patrocinados por el Organizador&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>en la red social Instagram, en relaci&oacute;n a la Promoci&oacute;n, durante el Plazo de Vigencia; (ii) hacer click en el&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>Posteo Patrocinado&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>que los derivar&aacute; a un Formulario; (iii) completar el Formulario con sus Datos de Contacto; (iv) ingresar una respuesta a la Pregunta que realizar&aacute; el Organizador en el Formulario; y (v) remitir su participaci&oacute;n haciendo click en &ldquo;Participar&rdquo;. Una vez cumplidos los pasos indicados, la Participaci&oacute;n se encontrar&aacute; completa.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>4.2.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;La carga completa de los Datos de Contacto y la respuesta a la Pregunta otorgar&aacute;n a cada Participante una (1) chance de convertirse en Ganador en el marco de la presente Promoci&oacute;n. Cada Participante s&oacute;lo podr&aacute; participar una (1) vez en la presente Promoci&oacute;n por cada red social. Ser&aacute;n descalificados los Participantes que no completen el formulario con sus Datos de Contacto, quienes no lo completen correctamente o de forma completa, o quienes no contesten la Pregunta. Est&aacute; prohibido y ser&aacute; anulado cualquier intento o m&eacute;todo de participaci&oacute;n en la Promoci&oacute;n que se realice por cualquier proceso, t&eacute;cnica o mec&aacute;nica de participaci&oacute;n distinta a la detallada en estas Bases. El Organizador se reserva la facultad de descalificar a los Participantes que de cualquier forma no cumplieren con lo establecido en estas Bases.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>4.3.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;El Organizador se reserva el derecho de admisi&oacute;n y participaci&oacute;n en la Promoci&oacute;n, estando facultado para ordenar el inmediato retiro y/o descalificaci&oacute;n de cualquier Participante si considerase que los datos ingresados al momento de su Participaci&oacute;n son ofensivos y/o de mal gusto y/o contrarios a la moral y buenas costumbres y/o cualquier otra circunstancia que, a exclusivo criterio del Organizador, pudiera suponer la desafectaci&oacute;n del Participante de la Promoci&oacute;n.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>4.4.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Todos los Participantes, por el solo hecho de responder a la Pregunta, autom&aacute;ticamente ceden al Organizador sus derechos sobre dichas respuestas conforme fueren registradas y autorizan expresamente a que el Organizador edite y/o publique su nombre y/o su respuesta a l Pregunta en plataformas digitales, redes sociales, TV, Radio, Digital, V&iacute;a P&uacute;blica y cualquier otro medio de comunicaci&oacute;n a los efectos y/o en relaci&oacute;n a la Promoci&oacute;n, sin l&iacute;mites temporales ni geogr&aacute;ficos, y sin derecho a contraprestaci&oacute;n alguna a favor del Participante. Cada Participante garantiza que ha obtenido cualquier consentimiento y/o autorizaciones necesarias para la explotaci&oacute;n de la respuesta a la Pregunta, y todos los fragmentos, nombres y personajes en ellos contenidos conforme se indicara anteriormente, incluyendo derechos de autor, derechos de imagen y cualquier otro que fuera exigible. Los Participantes manifiestan que mantendr&aacute;n indemne al Organizador por cualquier reclamo que fuese presentado ante el Organizador a causa de la falsedad o insuficiencia de la garant&iacute;a referida.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>5. SORTEO.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>5.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;El d&iacute;a 8 de Marzo de 2022, a las 14:00hs. se realizar&aacute; un sorteo (en adelante, el &ldquo;Sorteo&rdquo;) en las oficinas del Organizador, en presencia de un escribano p&uacute;blico, tom&aacute;ndose como base todas las Participaciones v&aacute;lidas ingresadas durante el Plazo de Vigencia, entre las cuales se seleccionar&aacute; al azar a trav&eacute;s de una f&oacute;rmula rand&oacute;mica quince (15) Participaciones cuyos remitentes ser&aacute;n considerados Potenciales Ganadores (en adelante, el/los &ldquo;Potencial/es Ganador/es&rdquo;) de un (1) Premio,</span><span style='font-family:"Cambria",serif;color:black;'>&nbsp;conforme m&aacute;s adelante se define</span><span style='font-family:"Cambria",serif;color:black;'>. Al mismo tiempo, se seleccionar&aacute; una (1) Participaci&oacute;n adicional por cada Potencial Ganador, cuyos titulares ser&aacute;n considerados, en orden de selecci&oacute;n, Potenciales Ganadores Suplentes (en adelante, el/los &ldquo;Potencial/es Ganador/es Suplente/s&rdquo;) para el supuesto en el que el Potencial Ganador seleccionado en primer t&eacute;rmino, por el motivo que fuere, no cumpliese con los recaudos exigidos para la participaci&oacute;n, asignaci&oacute;n y/o entrega de los Premios.&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>Cada Participante se encuentra facultado a ser Potencial Ganador de uno (1) solo de los Premios, en consecuencia, una vez que resulte Potencial Ganador quedar&aacute; autom&aacute;ticamente vedado a continuar participando en la Promoci&oacute;n por alguno de los restantes Premios.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>6</span></strong><strong><span style='font-family:"Cambria",serif;color:black;'>.&nbsp;</span></strong><strong><span style='font-family:"Cambria",serif;color:black;'>PREMIOS.&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>6.1.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>Los Premios (en adelante, el/los &ldquo;Premio/s&rdquo;) puestos en juego en esta Promoci&oacute;n ser&aacute;n quince (15) pares de entrada (en adelante, las &ldquo;entradas&rdquo;), compuesto por:&nbsp;</span></p>
                <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'>
                    <ul style="margin-bottom:0cm;list-style-type: disc;">
                        <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Cambria",serif;color:black;'>Dos (2) e</span><span style='font-family:"Cambria",serif;color:black;'>ntradas para que cada Ganador y un (1) acompa&ntilde;ante asistan al evento &ldquo;LOLLAPALOOZA 2022&rdquo; a realizarse el d&iacute;a 18, 19 y 20 de Marzo de 2022 a las 23:30hs en &ldquo;Hip&oacute;dromo de San Isidro&rdquo;, sito en Avenida Bernab&eacute; M&aacute;rquez, ciudad de San Isidro, provincia de Buenos Aires (en adelante, el &ldquo;Evento&rdquo;).</span></li>
                    </ul>
                </div>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>6.2.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Le corresponder&aacute; un (1) Premio a cada Ganador, es decir, dos (2) entradas</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;color:black;'>&nbsp;a cada Ganador.&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>Los Premios no incluyen ninguna otra prestaci&oacute;n, bien o servicio distinto de los expresamente detallados.&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>Los Premios ser&aacute;n intransferibles y no ser&aacute;n canjeables por dinero o bienes. Los Ganadores no podr&aacute;n solicitar su reemplazo ni sustituci&oacute;n por ning&uacute;n otro bien, servicio, ni prestaci&oacute;n distinta de la indicada en estas Bases, aun cuando, por cualquier circunstancia, no pudieran disfrutar de los mismos.&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>Los Premios no podr&aacute;n ser retirados y/o recibidos y/o utilizados, seg&uacute;n el caso, por terceros, ni tampoco transferidos a terceros.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>6.3.</span></strong><span style='font-family:"Cambria",serif;'>&nbsp;Todos los costos que se deriven de la obtenci&oacute;n, uso o ejercicio de los Premios de la Promoci&oacute;n fuera de lo estipulado en estas Bases, as&iacute; como todo impuesto, tasa, contribuci&oacute;n, arancel o suma de dinero que deba eventualmente abonarse o se imponga en el futuro sobre los Premios o su ofrecimiento a favor del Estado Nacional, sociedades del estado, provincias o municipalidades, estar&aacute;n a exclusivo cargo de cada Ganador. Por otra parte, todos los gastos en que incurra cada Ganador como consecuencia de su participaci&oacute;n en la presente, la obtenci&oacute;n de los Premios, entrega y utilizaci&oacute;n de los mismos, incluyendo, sin limitaci&oacute;n, los gastos de traslado y estad&iacute;a en que incurran para procurar la asignaci&oacute;n y/o retiro del Premio correspondiente, estar&aacute;n a exclusivo cargo de cada Ganador.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>6.4.</span></strong><span style='font-family:"Cambria",serif;'>&nbsp;Se encuentra terminantemente prohibido para cada Ganador la venta y/u ofrecimiento de venta de los Premios, ya sea en forma directa como a trav&eacute;s de terceros (Ej. sitios web especializados). Todo acto por parte de los Ganadores contrario a lo dispuesto en el presente p&aacute;rrafo habilitar&aacute; al Organizador o a quien corresponda, a intimar al Ganador infractor a la inmediata devoluci&oacute;n del Premio correspondiente, y a iniciar contra el mismo las acciones judiciales del caso.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>7.</span></strong><span style='font-family:"Cambria",serif;'>&nbsp;<strong>NOTIFICACI&Oacute;N A LOS POTENCIALES GANADORES, ASIGNACI&Oacute;N Y ENTREGA DE LOS PREMIOS&nbsp;</strong></span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>7.1.&nbsp;</span></strong><span style='font-family:"Cambria",serif;'>Cada Potencial Ganador ser&aacute; notificado de su condici&oacute;n&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>por&nbsp;</span><span style='font-family:"Cambria",serif;'>v&iacute;a telef&oacute;nica,&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>a trav&eacute;s del n&uacute;mero +54 1130029712 &nbsp;</span><span style='font-family:"Cambria",serif;'>dentro de las dos (2) horas posteriores a la realizaci&oacute;n del Sorteo. Los Potenciales Ganadores deber&aacute;n responder dicha comunicaci&oacute;n dentro de las veinticuatro (24) horas corridas de haber sido notificado de su condici&oacute;n de tales,&nbsp;</span><span style='font-family:"Cambria",serif;'>caso contrario, se los tendr&aacute; por desistidos del Premio&nbsp;</span><span style='font-family:"Cambria",serif;'>correspondiente&nbsp;</span><span style='font-family:"Cambria",serif;'>y se pasar&aacute; a contactar al Potencial Ganador Suplente que corresponda. Tras su respuesta, el Organizador le informar&aacute; a los Potenciales Ganadores la fecha, hora y lugar del acto de asignaci&oacute;n del Premio</span><span style='font-family:"Cambria",serif;'>&nbsp;correspondiente&nbsp;</span><span style='font-family:"Cambria",serif;'>(en adelante, el &ldquo;Acto de Asignaci&oacute;n&rdquo;), el cual se desarrollar&aacute; en presencia de un escribano p&uacute;blico.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>7.2.</span></strong><span style='font-family:"Cambria",serif;'>&nbsp;Ser&aacute; condici&oacute;n para la adjudicaci&oacute;n de los Premios</span><span style='font-family:"Cambria",serif;'>&nbsp;</span><span style='font-family:"Cambria",serif;'>que al momento del Acto de Asignaci&oacute;n, cada Potencial Ganador concurra personalmente, exhiba su Documento Nacional de Identidad, y conteste correctamente dos (2) de las tres (3) preguntas de cultura general que le formular&aacute; el personal del Organizador. Si los Datos de Contacto brindados no coincidieran con los datos personales que figuran en su documento de identidad, o si &eacute;ste no respondiere correctamente al menos dos (2) de las tres (3) preguntas de cultura general que se le formulen, o si de alguna manera no cumpliere con lo establecido en estas Bases, dicho Potencial Ganador quedar&aacute; autom&aacute;ticamente descalificado, perder&aacute; el derecho a que el Premio</span><span style='font-family:"Cambria",serif;'>&nbsp;correspondiente&nbsp;</span><span style='font-family:"Cambria",serif;'>le sea adjudicado, y se pasar&aacute; a contactar al Potencial Ganador Suplente correspondiente en su reemplazo, de conformidad con lo dispuesto en 7.1., a los fines de coordinar un nuevo Acto de Asignaci&oacute;n. De confirmarse la validez y legalidad de la participaci&oacute;n del Potencial Ganador (o en su caso del Potencial Ganador Suplente que reemplace al Potencial Ganador) y que &eacute;ste cumpla con lo referido anteriormente, se constituir&aacute; en Ganador de la Promoci&oacute;n (en adelante, el &ldquo;Ganador&rdquo;).&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>7.3.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>El Premio le ser&aacute; entregada al Ganador al finalizar el Acto de Asignaci&oacute;n.</span><strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>Ser&aacute; condici&oacute;n para la entrega de los Premios que cada Ganador suscriba el correspondiente recibo de entrega del Premio y preste conformidad por escrito a las presentes Bases.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>7.4.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Se deja constancia que la falta de retiro y/o recepci&oacute;n y/o uso de los Premios por parte de los Ganadores en el momento en que se le indicase, por cualquier motivo o causa que fuera, incluyendo caso fortuito y/o fuerza mayor, har&aacute; perder en forma autom&aacute;tica el derecho al Premio correspondiente y a formular reclamo alguno como consecuencia de la participaci&oacute;n en la Promoci&oacute;n. En tal caso, el Premio quedar&aacute; en poder del Organizador.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>7.5.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>Si alguno de los Premios resultase no asignado por motivos ajenos al Organizador, quedar&aacute; en poder del Organizador.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>8</span></strong><strong><span style='font-family:"Cambria",serif;'>. RESPONSABILIDAD.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>8.1.</span></strong><span style='font-family:"Cambria",serif;'>&nbsp;El Organizador no se responsabiliza de los da&ntilde;os, p&eacute;rdidas (directas, indirectas y/o consecuentes), hurtos y/o robos de los que pudieran ser objeto los Participantes, y/o los Potenciales Ganadores, y/o los Ganadores y/o terceras personas, con motivo o en ocasi&oacute;n de su participaci&oacute;n y/o retiro y/o recepci&oacute;n de los Premios y/o durante el uso de los Premios. El Organizador no ser&aacute; responsable: (i) por ning&uacute;n da&ntilde;o o perjuicio, de cualquier tipo que fuere, que pudieren sufrir los Potenciales Ganadores, los Ganadores o terceros, sobre sus personas o bienes, con motivo de o en relaci&oacute;n a su participaci&oacute;n en la presente&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>Promoci&oacute;n</span><span style='font-family:"Cambria",serif;'>, o por el uso del Premio correspondiente obtenido, declinando todo tipo de responsabilidad contractual y/o extracontractual frente a los Potenciales Ganadores, los Ganadores, acompa&ntilde;antes, terceros y/o sus sucesores, lo que es aceptado incondicionalmente por cada Participante; y (ii) por fallas en Internet, en la red telef&oacute;nica, en el servicio de correo postal, ni por desperfectos t&eacute;cnicos y/o por errores humanos o acciones deliberadas de terceros que pudieran interrumpir o alterar el desarrollo de la&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>Promoci&oacute;n</span><span style='font-family:"Cambria",serif;'>. El Organizador no otorga garant&iacute;a de calidad ni ninguna otra en relaci&oacute;n con los Premios que no fueren fabricados o elaborados por &eacute;ste, debiendo dirigirse cualquier reclamo a los proveedores de los mismos.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>8.2.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;La responsabilidad del Organizador finaliza al poner a disposici&oacute;n de cada Ganador el Premio correspondiente y de ninguna manera se extiende al uso de los Premios, a la asistencia al Evento o el traslado de los Ganadores y/o sus acompa&ntilde;antes hacia el Evento, m&aacute;s all&aacute; de lo dispuesto en estas Bases. En caso de que el Evento deba suspenderse temporaria o definitivamente, por motivos&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>ajenos a la voluntad del Organizador</span><span style='font-family:"Cambria",serif;color:black;'>, incluyendo expresamente pero no limitado a&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>razones relacionadas a la pandemia de Covid-19,</span><span style='font-family:"Cambria",serif;color:black;'>&nbsp;el Organizador no tendr&aacute; responsabilidad alguna frente a los Ganadores y/o sus acompa&ntilde;antes. El Organizador no se responsabiliza de los da&ntilde;os, hurtos y/o robos de los que pudiera ser objeto los Ganadores y/o sus acompa&ntilde;antes y/o terceros durante el Evento o su traslado hacia y desde el mismo. Los gastos no incluidos en las presentes Bases estar&aacute;n a cargo de cada Ganador y/o sus acompa&ntilde;antes, incluyendo&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>pero sin limitarse gastos de vi&aacute;ticos y/o traslado y/o impuestos</span><span style='font-family:"Cambria",serif;color:black;'>&nbsp;y/o cualquier otro costo o gasto que se produzca como consecuencia y/o en ocasi&oacute;n del traslado y/o asistencia al Evento. Cada Ganador mantendr&aacute; indemne y a salvo al Organizador y a sus compa&ntilde;&iacute;as vinculadas, a sus agencias o afiliadas por cualquier da&ntilde;o, p&eacute;rdida y/o accidente acaecido en su persona como consecuencia de la utilizaci&oacute;n del Premio correspondiente.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>8.3.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>Los Ganadores y sus acompa&ntilde;antes aceptan y reconocen que la utilizaci&oacute;n del Premio y la asistencia al Evento son de riesgo, libre y voluntaria, lo que implica que pueden desistir de utilizar el Premio y/o asistir al Evento en cualquier momento, pero que en caso de proceder con su la utilizaci&oacute;n del Premio y/o asistir al Evento, las consecuencias de dicho accionar, incluidas expresamente aquellas derivadas de la situaci&oacute;n epidemiol&oacute;gica actual relacionada a la pandemia de Covid-19, ser&aacute;n de su &uacute;nica y exclusiva responsabilidad.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>8.4.</span></strong><span style='font-family:"Cambria",serif;'>&nbsp;Se deja expresa constancia, y los Participantes aceptan, que al asistir al Evento los Ganadores y sus acompa&ntilde;antes deber&aacute;n cumplir con todas las precauciones de seguridad necesarias siguiendo las &uacute;ltimas recomendaciones y gu&iacute;as de seguridad gubernamentales relativas al Covid-19, disponibles en https://www.argentina.gob.ar/salud/coronavirus/poblacion/prevencion, en especial aquellas relacionadas a la asistencia a eventos, como as&iacute; tambi&eacute;n todos aquellos protocolos establecidos por el&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>Evento.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>9. PROBABILIDAD MATEM&Aacute;TICA.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>9.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Las probabilidades de resultar favorecido y ser Potencial Ganador de alguno de los Premios, est&aacute;n sujetas al n&uacute;mero total de Participaciones registradas durante la totalidad del Plazo de Vigencia. En este sentido, y a modo de ejemplo, si un Participante hubiera ingresado una (1) Participaci&oacute;n v&aacute;lida, habi&eacute;ndose registrado una cantidad total de mil (1.000) Participaciones de las mismas caracter&iacute;sticas, las probabilidades de que el Participante resulte Ganador ser&aacute;n de cinco (5) en mil (1.000).</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>10. AUTORIZACI&Oacute;N.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>10.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Los Ganadores y/o los Potenciales Ganadores y/o Participantes de la Promoci&oacute;n autorizan expresamente al Organizador a difundir sus nombres, DNI, voz e imagen, con fines promocionales, en cualquier medio de comunicaci&oacute;n (incluido el sitio web del Organizador, Facebook, Instagram, etc.), sin derecho a compensaci&oacute;n alguna, durante el Plazo de Vigencia y hasta los tres (3) a&ntilde;os de finalizado dicho Plazo de Vigencia, de conformidad con lo dispuesto en la Ley 25.326. La presente autorizaci&oacute;n es condici&oacute;n de participaci&oacute;n en la presente Promoci&oacute;n.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>11. MEDIOS DE DIFUSI&Oacute;N DE LA PROMOCI&Oacute;N.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>11.1.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>Esta Promoci&oacute;n se difundir&aacute; a trav&eacute;s de la cuenta oficial de Axe en Instagram, @axeargentina (en adelante, la &ldquo;Cuenta de Instagram&rdquo;) y la cuenta oficial de Axe en Facebook, https://www.facebook.com/axeargentina/ (en adelante, la &ldquo;Fanpage&rdquo;).</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>12. PUBLICACI&Oacute;N DE BASES.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>12.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Las presentes Bases se encontrar&aacute;n disponibles en el sitio web https://www.axe.com/ar/basesycondiciones.html (en adelante, el &ldquo;Sitio&rdquo;) y en el domicilio del Organizador sito en Alf. H. Bouchard 4191, Munro, Ptdo. de Vte. L&oacute;pez, Prov. de Buenos Aires.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>13. DIFUSI&Oacute;N DE LOS GANADORES DE LA PROMOCI&Oacute;N.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>13.1</span></strong><span style='font-family:"Cambria",serif;color:black;'>. Los datos de los Ganadores ser&aacute;n anunciados en la Cuenta de Instagram y la Fanpage dentro de los siguientes treinta (30) d&iacute;as h&aacute;biles de la entrega de los Premios.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>14. IMPUESTOS.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>14.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Todo impuesto, gravamen, carga, retenci&oacute;n o similar (actual o futuro) que deba tributarse o se origine sobre o en relaci&oacute;n con los Premios, ser&aacute; a cargo de cada Ganador y/o sus acompa&ntilde;antes.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>15. MANIOBRAS QUE DESNATURALICEN LA PROMOCI&Oacute;N.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>15.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;El Organizador podr&aacute; prohibir la participaci&oacute;n en la Promoci&oacute;n como as&iacute; tambi&eacute;n podr&aacute; no otorgar los Premios a aquellas personas que, por si o vali&eacute;ndose de terceros, intenten socavar la operaci&oacute;n leg&iacute;tima de la Promoci&oacute;n por medio de trampas, fraudes, enga&ntilde;os, manipulaciones o cualquier otra pr&aacute;ctica desleal de juego destinada a ganar de forma ileg&iacute;tima, molestar, insultar, amenazar o acosar a otros Participantes, sin perjuicio del derecho de reclamar los da&ntilde;os y perjuicios irrogados como consecuencia de dicho proceder. Asimismo, el Organizador inhabilitar&aacute; a cualquier Participante o Potencial Ganador que haya realizado tal conducta o llevare a cabo conductas fraudulentas en contra de los mecanismos de participaci&oacute;n; como as&iacute; tambi&eacute;n si se detectara el uso de alg&uacute;n sistema inform&aacute;tico fraudulento y/o robot inform&aacute;tico. En tales circunstancias, el Organizador tendr&aacute; la facultad de analizar la conducta fraudulenta a trav&eacute;s de los t&eacute;cnicos y peritos que considere pertinente e iniciar las acciones legales que correspondan.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>16. BASE DE DATOS.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>16.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>Mediante el suministro de datos personales y/o Datos de Contacto (en adelante, los &ldquo;Datos&rdquo;) al Organizador y consecuente aceptaci&oacute;n de las presentes Bases, el Participante autoriza al Organizador a (i) utilizar los Datos proporcionados a los efectos de la Promoci&oacute;n; (ii) almacenarlos en una base de Datos; (iii) enviar e-mails con promociones, informaci&oacute;n y/o novedades relacionadas con los productos que comercializa o produce el Organizador, que a su exclusivo criterio pudieran resultar de inter&eacute;s de los Participantes; (iv) dar a conocer la base de Datos como as&iacute; tambi&eacute;n autorizar su uso a terceros, siempre que ello resulte necesario para llevar adelante la Promoci&oacute;n; (v) establecer perfiles y/o h&aacute;bitos de consumo con fines promocionales, de marketing y/o comerciales en general.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>16.2.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Todo Participante podr&aacute;, en cualquier momento, solicitar de manera gratuita la actualizaci&oacute;n y rectificaci&oacute;n de sus Datos contenidos en la base de Datos, como as&iacute; tambi&eacute;n el retiro o bloqueo total o parcial de los mismos, enviando una carta documento a las oficinas del Organizador, en la calle Alf. H. Bouchard 4191, Munro, Ptdo. de Vte. L&oacute;pez, Prov. de Buenos Aires, present&aacute;ndose personalmente en dichas oficinas de lunes a viernes de 11:00 horas a 17:00 horas., o comunic&aacute;ndose de forma gratuita al tel&eacute;fono 0800-888-6666.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>16.3.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita por intervalos no inferiores a seis (6) meses, salvo que se acredite un inter&eacute;s leg&iacute;timo al efecto conforme lo establecido en el art&iacute;culo 14, inciso 3, de la Ley N&ordm; 25.326.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>16.4.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;La AGENCIA DE ACCESO A LA INFORMACI&Oacute;N P&Uacute;BLICA, &Oacute;rgano de Control de la Ley N&ordm; 25.326, tiene la atribuci&oacute;n de atender las denuncias y reclamos que se interpongan con relaci&oacute;n al incumplimiento de las normas sobre protecci&oacute;n de datos personales.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>16.5.&nbsp;</span></strong><span style='font-family:"Cambria",serif;color:black;'>Para mayor informaci&oacute;n respecto de lo dispuesto en este apartado, por favor visite http://www.unileverprivacypolicy.com/spanish/policy.aspx.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>17. ACEPTACI&Oacute;N DE LAS BASES.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>17.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Por el hecho de participar en la presente Promoci&oacute;n, los Participantes reconocen estar sujetos total e irrestrictamente a las condiciones establecidas en las presentes Bases, las cuales podr&aacute;n ser consultadas en el Sitio&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>y en el domicilio del Organizador.</span><span style='font-family:"Cambria",serif;color:black;'>&nbsp;</span><span style='font-family:"Cambria",serif;color:black;'>La</span><span style='font-family:"Cambria",serif;color:black;'>&nbsp;participaci&oacute;n asimismo implica el reconocimiento de las decisiones que el Organizador tome con relaci&oacute;n a la Promoci&oacute;n como de car&aacute;cter definitivo e inapelable toda vez que las mismas no resulten abusivas ni infundadas, no perjudiquen dolosamente el derecho de los Participantes, se ajusten al r&eacute;gimen legal vigente y hayan sido comunicadas a los Participantes.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>18. SUSPENSI&Oacute;N, CANCELACI&Oacute;N, MODIFICACI&Oacute;N.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>18.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;El Organizador de la presente Promoci&oacute;n se reserva el derecho de cancelar, suspender o modificar la presente Promoci&oacute;n y/o Premios, siempre y cuando dichas decisiones no resulten abusivas ni infundadas, no perjudiquen dolosamente el derecho de los Participantes, se ajusten al r&eacute;gimen legal vigente y hayan sido comunicadas a los Participantes.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>19. FACEBOOK. INSTAGRAM.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><strong><span style='font-family:"Cambria",serif;'>19.1.&nbsp;</span></strong><span style='font-family:"Cambria",serif;'>Se deja expresamente aclarado que las redes sociales Facebook e Instagram no patrocinan, avalan, administran, ni est&aacute;n asociadas a la&nbsp;</span><span style='font-family:"Cambria",serif;'>Promoci&oacute;n</span><span style='font-family:"Cambria",serif;'>&nbsp;de ninguna forma. Los Participantes proporcionar&aacute;n su informaci&oacute;n al Organizador, no a Facebook, ni a Instagram. Dichas redes sociales quedan completamente exoneradas de toda responsabilidad respecto de la&nbsp;</span><span style='font-family:"Cambria",serif;'>Promoci&oacute;n&nbsp;</span><span style='font-family:"Cambria",serif;'>y su desarrollo.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:.05pt;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>20. NO ASOCIACI&Oacute;N CON UNILEVER DE ARGENTINA S.A.</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>20.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Se deja expresa constancia que LHR S.A. no tiene sociedad o relaci&oacute;n laboral de ning&uacute;n tipo con UNILEVER DE ARGENTINA S.A., manteniendo ambas su plena individualidad, independencia y autonom&iacute;a, para todo prop&oacute;sito.&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>21. LEY APLICABLE. JURISDICCI&Oacute;N</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;color:black;'>21.1.</span></strong><span style='font-family:"Cambria",serif;color:black;'>&nbsp;Todas divergencias que pudieran surgir con relaci&oacute;n a esta Promoci&oacute;n y a todos los efectos de la misma, las partes se someten a la Ley de la Rep&uacute;blica Argentina y a la jurisdicci&oacute;n y competencia de los tribunales ordinarios de la Ciudad Aut&oacute;noma de Buenos Aires, renunciando a cualquier otro que les pudiera corresponder.</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><strong><span style='font-family:"Cambria",serif;'>&nbsp;</span></strong></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;color:black;'>Febrero de 2022</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;'>&nbsp;</span></p>
                <p style='margin-top:0cm;margin-right:0cm;margin-bottom:0cm;margin-left:0cm;line-height:115%;font-size:15px;font-family:"Calibri",sans-serif;text-align:justify;background:white;'><span style='font-family:"Cambria",serif;color:black;'>Unilever de Argentina S.A.</span></p>

            </div>
              <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>

            </div>
          </div>
        </div>
      </div>

-->
      <!-- Se cierra Modal -->
